language: php

dist: precise

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --no-progress

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit tests
