language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --no-progress

script:
  - composer validate --strict
  - vendor/bin/phpcs src
  - vendor/bin/phpunit
